---
- name:                Deploy chosen artifakt to QA-env
  get_url:
    force: yes
    url: "{{ artifact_url }}"
    dest: "{{ artifact_dest }}"
    username: "{{ repository_user }}"
    password: "{{ repository_password }}"

- name:                 Kill process on port 8888
  ignore_errors: yes
  shell:
    kill -9 $(lsof -t -i:8888)

- name:                 Run downloaded artifact on CI environment
  shell:
    nohup java -jar "{{ artifact_dest }}" --server.port=8888 &

