---
- name:                 Download artifact from Nexus
  maven_artifact:
    repository_url:     "{{ repository_url }}"
    group_id:           "{{ group_id }}"
    artifact_id:        "{{ artifact_id }}"
    version:            "{{ artifact_version }}"
    extension:          "{{ artifact_extension }}"
    dest:               "{{ artifact_dest }}"

- name:                 Run downloaded artifact on CI environment
  shell:
    nohup java -jar "{{ artifact_dest }}" --server.port=8888 &
