---
- name: deploying artifact from nexus to work enwironment and start app
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files: ./group_vars/build_vars.yml

  roles:
    - deploy_artifact
